const ownGameText = {
    pl: {
        seoPageTitle: "Prywatne czytanie",
        seoPageDescription: "Czy kiedykolwiek zastanawiałeś się, co przyniesie Ci przyszłość? Czy marzysz o jasności w swojej ścieżce życiowej? Nasza usługa odczytu kart tarota jest tu, by pomóc Ci rozwikłać tajemnice przyszłości i prowadzić Cię ku pełni życia.",
        pageTitle: "Co Oferujemy:",
        pageLinePoint0: "Indywidualne Podejście",
        pageLineDesc0: "Każdy odczyt jest dostosowany do Twoich unikalnych potrzeb i pytań. Nasze doświadczone tarociarki podejdą do Ciebie z empatią i zrozumieniem.",
        pageLinePoint1: "Pełne Zrozumienie",
        pageLineDesc1: "Odkryj głębokie znaczenie kart tarota i ich wpływ na Twoje życie. Nasze sesje nie tylko przewidują przyszłość, ale także pomagają w zrozumieniu Twoich wyborów i emocji.",
        pageLinePoint2: "Wsparcie w Podjęciu Decyzji",
        pageLineDesc2: "Tarot może być świetnym narzędziem do uzyskania wskazówek dotyczących decyzji życiowych. Otrzymasz jasność i pewność, której potrzebujesz.",
        pageLinePoint3: "Prywatność i Bezpieczeństwo",
        pageLineDesc3: "Gwarantujemy pełną prywatność. Twoje pytania i odpowiedzi są chronione tajemnicą. Możesz czuć się swobodnie dzieląc się swoimi myślami.",
        pageSectionHowWord: "Jak to działa:",
        pageSectionPrice: "Cena:",
        pageSectionDesc: " Ceny to jedyne 25zł. Zamów Teraz i Odkryj Swój Los!",
        pageSectionOwn: "Zamów własne czytanie",
        pageFormOrderButton: "Zamów",
        pageFormOrderFieldRequired: "Pole wymagane",
        pageFormOrderFieldName: "Imię",
        pageFormOrderFieldDate: "Data urodzenia",
        pageFormOrderFieldSex: "Płeć",
        pageFormOrderFieldType: "Typ wróźby",
        pageFormOrderFieldEmail: "Adres email",
        pageFormOrderFieldSexMen: "Mężczyzna",
        pageFormOrderFieldSexWomen: "Kobieta",
        pageFormOrderFieldTypeDefault: "Ogólna",
        pageFormOrderFieldTypeLove: "Miłość",
        pageFormOrderFieldTypeWork: "Praca",
        pageFormOrderFieldTypeHealth: "Zdrowie",
    },
    en: {
        "seoPageTitle": "Private Reading",
        "seoPageDescription": "Have you ever wondered what the future holds for you? Do you dream of clarity in your life's path? Our tarot card reading service is here to help unravel the mysteries of the future and guide you towards a fulfilling life.",
        "pageTitle": "What We Offer:",
        "pageLinePoint0": "Individual Approach",
        "pageLineDesc0": "Each reading is tailored to your unique needs and questions. Our experienced tarot readers approach you with empathy and understanding.",
        "pageLinePoint1": "Full Understanding",
        "pageLineDesc1": "Discover the deep meanings of tarot cards and their impact on your life. Our sessions not only predict the future but also help you understand your choices and emotions.",
        "pageLinePoint2": "Decision Support",
        "pageLineDesc2": "Tarot can be a great tool for getting insights into life decisions. You'll gain clarity and confidence that you need.",
        "pageLinePoint3": "Privacy and Security",
        "pageLineDesc3": "We guarantee complete privacy. Your questions and answers are kept confidential. Feel free to share your thoughts.",
        "pageSectionHowWord": "How It Works:",
        "pageSectionPrice": "Price:",
        "pageSectionDesc": "Prices are only 10 EURO. Order Now and Discover Your Fate!",
        "pageSectionOwn": "Order Your Own Reading",
        "pageFormOrderButton": "Order",
        "pageFormOrderFieldRequired": "Required Field",
        "pageFormOrderFieldName": "Name",
        "pageFormOrderFieldDate": "Date of Birth",
        "pageFormOrderFieldSex": "Gender",
        "pageFormOrderFieldType": "Type of Reading",
        "pageFormOrderFieldEmail": "Email Address",
        "pageFormOrderFieldSexMen": "Male",
        "pageFormOrderFieldSexWomen": "Female",
        "pageFormOrderFieldTypeDefault": "General",
        "pageFormOrderFieldTypeLove": "Love",
        "pageFormOrderFieldTypeWork": "Work",
        "pageFormOrderFieldTypeHealth": "Health"
    }
    ,
    fr: {
        "seoPageTitle": "Lecture privée",
        "seoPageDescription": "Vous êtes-vous déjà demandé ce que l'avenir vous réserve ? Rêvez-vous de clarté sur le chemin de votre vie ? Notre service de lecture de cartes de tarot est là pour vous aider à démêler les mystères de l'avenir et à vous guider vers une vie épanouissante.",
        "pageTitle": "Ce que nous proposons :",
        "pageLinePoint0": "Approche individuelle",
        "pageLineDesc0": "Chaque lecture est adaptée à vos besoins et questions uniques. Nos lecteurs de tarot expérimentés vous abordent avec empathie et compréhension.",
        "pageLinePoint1": "Compréhension totale",
        "pageLineDesc1": "Découvrez les significations profondes des cartes de tarot et leur impact sur votre vie. Nos sessions ne prédisent pas seulement l'avenir, mais vous aident également à comprendre vos choix et vos émotions.",
        "pageLinePoint2": "Soutien à la prise de décision",
        "pageLineDesc2": "Le tarot peut être un excellent outil pour obtenir des éclaircissements sur les décisions de vie. Vous obtiendrez la clarté et la confiance dont vous avez besoin.",
        "pageLinePoint3": "Confidentialité et sécurité",
        "pageLineDesc3": "Nous garantissons une confidentialité totale. Vos questions et réponses sont traitées de manière confidentielle. N'hésitez pas à partager vos pensées.",
        "pageSectionHowWord": "Comment ça marche :",
        "pageSectionPrice": "Prix :",
        "pageSectionDesc": "Les prix ne sont que de 10 EURO. Commandez maintenant et découvrez votre destin !",
        "pageSectionOwn": "Commandez votre propre lecture",
        "pageFormOrderButton": "Commander",
        "pageFormOrderFieldRequired": "Champ obligatoire",
        "pageFormOrderFieldName": "Nom",
        "pageFormOrderFieldDate": "Date de naissance",
        "pageFormOrderFieldSex": "Genre",
        "pageFormOrderFieldType": "Type de lecture",
        "pageFormOrderFieldEmail": "Adresse e-mail",
        "pageFormOrderFieldSexMen": "Homme",
        "pageFormOrderFieldSexWomen": "Femme",
        "pageFormOrderFieldTypeDefault": "Général",
        "pageFormOrderFieldTypeLove": "Amour",
        "pageFormOrderFieldTypeWork": "Travail",
        "pageFormOrderFieldTypeHealth": "Santé"
    }
    ,
    de: {
        "seoPageTitle": "Private Lesung",
        "seoPageDescription": "Hast du dich jemals gefragt, was die Zukunft für dich bereithält? Träumst du von Klarheit auf deinem Lebensweg? Unser Tarot-Kartendeutungsdienst ist hier, um dir zu helfen, die Geheimnisse der Zukunft zu enträtseln und dich auf ein erfülltes Leben zu führen.",
        "pageTitle": "Was wir anbieten:",
        "pageLinePoint0": "Individueller Ansatz",
        "pageLineDesc0": "Jede Lesung wird an deine einzigartigen Bedürfnisse und Fragen angepasst. Unsere erfahrenen Tarot-Leser kommen einfühlsam und verständnisvoll auf dich zu.",
        "pageLinePoint1": "Vollständiges Verständnis",
        "pageLineDesc1": "Entdecke die tiefen Bedeutungen der Tarotkarten und ihren Einfluss auf dein Leben. Unsere Sitzungen sagen nicht nur die Zukunft voraus, sondern helfen dir auch, deine Entscheidungen und Emotionen zu verstehen.",
        "pageLinePoint2": "Unterstützung bei Entscheidungen",
        "pageLineDesc2": "Tarot kann ein ausgezeichnetes Werkzeug sein, um Hinweise für lebenswichtige Entscheidungen zu erhalten. Du erhältst die Klarheit und Sicherheit, die du brauchst.",
        "pageLinePoint3": "Privatsphäre und Sicherheit",
        "pageLineDesc3": "Wir garantieren vollständige Privatsphäre. Deine Fragen und Antworten werden vertraulich behandelt. Du kannst dich frei fühlen, deine Gedanken zu teilen.",
        "pageSectionHowWord": "Wie funktioniert es:",
        "pageSectionPrice": "Preis:",
        "pageSectionDesc": "Die Kosten betragen nur 10 EURO. Bestelle jetzt und entdecke dein Schicksal!",
        "pageSectionOwn": "Bestelle deine eigene Lesung",
        "pageFormOrderButton": "Bestellen",
        "pageFormOrderFieldRequired": "Pflichtfeld",
        "pageFormOrderFieldName": "Name",
        "pageFormOrderFieldDate": "Geburtsdatum",
        "pageFormOrderFieldSex": "Geschlecht",
        "pageFormOrderFieldType": "Art der Deutung",
        "pageFormOrderFieldEmail": "E-Mail-Adresse",
        "pageFormOrderFieldSexMen": "Mann",
        "pageFormOrderFieldSexWomen": "Frau",
        "pageFormOrderFieldTypeDefault": "Allgemein",
        "pageFormOrderFieldTypeLove": "Liebe",
        "pageFormOrderFieldTypeWork": "Arbeit",
        "pageFormOrderFieldTypeHealth": "Gesundheit"
    }
    ,
    it: {
        "seoPageTitle": "Lettura Privata",
        "seoPageDescription": "Ti sei mai chiesto cosa riserva il futuro per te? Sogni chiarezza nel tuo percorso di vita? Il nostro servizio di lettura delle carte del tarocchi è qui per aiutarti a svelare i segreti del futuro e guidarti verso una vita appagante.",
        "pageTitle": "Cosa Offriamo:",
        "pageLinePoint0": "Approccio Individuale",
        "pageLineDesc0": "Ogni lettura è adattata alle tue esigenze e domande uniche. I nostri esperti lettori di tarocchi si avvicineranno a te con empatia e comprensione.",
        "pageLinePoint1": "Comprensione Completa",
        "pageLineDesc1": "Scopri il significato profondo delle carte del tarocchi e il loro impatto sulla tua vita. Le nostre sessioni non solo predicono il futuro, ma ti aiutano anche a comprendere le tue scelte ed emozioni.",
        "pageLinePoint2": "Supporto nella Presa di Decisioni",
        "pageLineDesc2": "Il tarocchi può essere uno strumento eccellente per ottenere indicazioni su decisioni importanti. Otterrai chiarezza e sicurezza di cui hai bisogno.",
        "pageLinePoint3": "Privacy e Sicurezza",
        "pageLineDesc3": "Garantiamo piena privacy. Le tue domande e risposte sono trattate con riservatezza. Puoi sentirti libero di condividere i tuoi pensieri.",
        "pageSectionHowWord": "Come Funziona:",
        "pageSectionPrice": "Prezzo:",
        "pageSectionDesc": "Il costo è solo di 10 EURO. Ordina Ora e Scopri il Tuo Destino!",
        "pageSectionOwn": "Ordina la tua lettura personale",
        "pageFormOrderButton": "Ordina",
        "pageFormOrderFieldRequired": "Campo Obbligatorio",
        "pageFormOrderFieldName": "Nome",
        "pageFormOrderFieldDate": "Data di Nascita",
        "pageFormOrderFieldSex": "Genere",
        "pageFormOrderFieldType": "Tipo di Lettura",
        "pageFormOrderFieldEmail": "Indirizzo Email",
        "pageFormOrderFieldSexMen": "Uomo",
        "pageFormOrderFieldSexWomen": "Donna",
        "pageFormOrderFieldTypeDefault": "Generale",
        "pageFormOrderFieldTypeLove": "Amore",
        "pageFormOrderFieldTypeWork": "Lavoro",
        "pageFormOrderFieldTypeHealth": "Salute"
    }
    ,
    nl: {
        "seoPageTitle": "Privé Lezing",
        "seoPageDescription": "Heb je je ooit afgevraagd wat de toekomst voor jou in petto heeft? Droom je van helderheid op je levenspad? Onze tarotkaartlezingsservice is er om je te helpen de geheimen van de toekomst te ontrafelen en je te leiden naar een vervullend leven.",
        "pageTitle": "Wat Bieden We Aan:",
        "pageLinePoint0": "Individuele Benadering",
        "pageLineDesc0": "Elke lezing is afgestemd op jouw unieke behoeften en vragen. Onze ervaren tarotlezers benaderen je met empathie en begrip.",
        "pageLinePoint1": "Volledig Begrip",
        "pageLineDesc1": "Ontdek de diepere betekenis van tarotkaarten en hun invloed op je leven. Onze sessies voorspellen niet alleen de toekomst, maar helpen je ook je keuzes en emoties te begrijpen.",
        "pageLinePoint2": "Ondersteuning bij Besluitvorming",
        "pageLineDesc2": "Tarot kan een uitstekend hulpmiddel zijn om aanwijzingen te krijgen voor belangrijke beslissingen. Je krijgt helderheid en zekerheid die je nodig hebt.",
        "pageLinePoint3": "Privacy en Veiligheid",
        "pageLineDesc3": "Wij garanderen volledige privacy. Jouw vragen en antwoorden worden vertrouwelijk behandeld. Je kunt vrijuit je gedachten delen.",
        "pageSectionHowWord": "Hoe Werkt Het:",
        "pageSectionPrice": "Prijs:",
        "pageSectionDesc": "De kosten zijn slechts 10 EURO. Bestel Nu en Ontdek Je Lot!",
        "pageSectionOwn": "Bestel je eigen lezing",
        "pageFormOrderButton": "Bestel",
        "pageFormOrderFieldRequired": "Verplicht Veld",
        "pageFormOrderFieldName": "Naam",
        "pageFormOrderFieldDate": "Geboortedatum",
        "pageFormOrderFieldSex": "Geslacht",
        "pageFormOrderFieldType": "Type Voorspelling",
        "pageFormOrderFieldEmail": "E-mailadres",
        "pageFormOrderFieldSexMen": "Man",
        "pageFormOrderFieldSexWomen": "Vrouw",
        "pageFormOrderFieldTypeDefault": "Algemeen",
        "pageFormOrderFieldTypeLove": "Liefde",
        "pageFormOrderFieldTypeWork": "Werk",
        "pageFormOrderFieldTypeHealth": "Gezondheid"
    }
    ,
    es: {
        "seoPageTitle": "Lectura Privada",
        "seoPageDescription": "¿Alguna vez te has preguntado qué te depara el futuro? ¿Sueñas con claridad en tu camino de vida? Nuestro servicio de lectura de cartas del tarot está aquí para ayudarte a desentrañar los secretos del futuro y guiarte hacia una vida plena.",
        "pageTitle": "Lo Que Ofrecemos:",
        "pageLinePoint0": "Enfoque Individual",
        "pageLineDesc0": "Cada lectura se adapta a tus necesidades y preguntas únicas. Nuestros experimentados lectores de tarot se acercarán a ti con empatía y comprensión.",
        "pageLinePoint1": "Comprensión Completa",
        "pageLineDesc1": "Descubre el significado profundo de las cartas del tarot y su influencia en tu vida. Nuestras sesiones no solo predicen el futuro, sino que también te ayudan a entender tus elecciones y emociones.",
        "pageLinePoint2": "Apoyo en la Toma de Decisiones",
        "pageLineDesc2": "El tarot puede ser una excelente herramienta para obtener orientación en decisiones importantes. Obtendrás claridad y certeza que necesitas.",
        "pageLinePoint3": "Privacidad y Seguridad",
        "pageLineDesc3": "Garantizamos completa privacidad. Tus preguntas y respuestas están protegidas con confidencialidad. Siéntete libre de compartir tus pensamientos.",
        "pageSectionHowWord": "Cómo Funciona:",
        "pageSectionPrice": "Precio:",
        "pageSectionDesc": "El costo es solo de 10 EURO. ¡Ordena Ahora y Descubre Tu Destino!",
        "pageSectionOwn": "Ordena Tu Propia Lectura",
        "pageFormOrderButton": "Ordenar",
        "pageFormOrderFieldRequired": "Campo Obligatorio",
        "pageFormOrderFieldName": "Nombre",
        "pageFormOrderFieldDate": "Fecha de Nacimiento",
        "pageFormOrderFieldSex": "Género",
        "pageFormOrderFieldType": "Tipo de Predicción",
        "pageFormOrderFieldEmail": "Correo Electrónico",
        "pageFormOrderFieldSexMen": "Hombre",
        "pageFormOrderFieldSexWomen": "Mujer",
        "pageFormOrderFieldTypeDefault": "General",
        "pageFormOrderFieldTypeLove": "Amor",
        "pageFormOrderFieldTypeWork": "Trabajo",
        "pageFormOrderFieldTypeHealth": "Salud"
    }
} as const;

export default ownGameText;